on:
  pull_request:
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/**'
name: Test
jobs:
  jobAutomation:
    name: Automation Deploy Tokens
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'momentum-design' }}
    steps:
    - name: Check out
      uses: actions/checkout@master
      with:
          fetch-depth: 2
    - name: Install Package and Build
      run: npm run init-build
    - name: Test release data
      run: npm run test]
